export const burger = [
  { name: "Hamburguer", price: 150 },
  { name: "Calzone", price: 150 },
  { name: "Frango frito", price: 125 },
  { name: "Fritas com bacon", price: 75 },
  { name: "Anéis de cebola", price: 100 },
  { name: "Cookie", price: 60 },
  { name: "Sucos", price: 125 },
  { name: "Suco de maracujá", price: 150 },
  { name: "Guaraná", price: 100 },
  { name: "Café com leite", price: 100 },
  { name: "Energético", price: 75 },
  { name: "Combo 1", price: 825 },
  { name: "Combo 1 + Mar", price: 900 },
  { name: "Milkshake", price: 125 },
  { name: "Milkshake", price: 125 },
  { name: "Milkshake", price: 125 },
  { name: "Milkshake", price: 125 },
];
